{
 "title": "GBFS Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "CitiBike",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "`gbfs-database`",
     "rawSql": "SELECT \n    DATE_FORMAT(timestamp, '%H:%i') AS time_bucket, -- Round timestamp to minute\n    AVG(total_bikes) AS avg_total_bikes,\n    AVG(available_docks) AS avg_available_docks\nFROM gbfs_stats\nWHERE provider = 'CitiBike' AND $__timeFilter(timestamp)\nGROUP BY time_bucket\nORDER BY time_bucket;\n"
    }
   ]
  },
  {
   "title": "Careem",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "`gbfs-database`",
     "rawSql": "SELECT \n    DATE_FORMAT(timestamp, '%H:%i') AS time_bucket, -- Round timestamp to minute\n    AVG(total_bikes) AS avg_total_bikes,\n    AVG(available_docks) AS avg_available_docks\nFROM gbfs_stats\nWHERE provider = 'Careem' AND $__timeFilter(timestamp)\nGROUP BY time_bucket\nORDER BY time_bucket;\n"
    }
   ]
  },
  {
   "title": "Nextbike",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "`gbfs-database`",
     "rawSql": "SELECT \n    DATE_FORMAT(timestamp, '%H:%i') AS time_bucket, -- Round timestamp to minute\n    AVG(total_bikes) AS avg_total_bikes,\n    AVG(available_docks) AS avg_available_docks\nFROM gbfs_stats\nWHERE provider = 'Nextbike' AND $__timeFilter(timestamp)\nGROUP BY time_bucket\nORDER BY time_bucket;\n"
    }
   ]
  }
 ]
}