name: CD Workflow

on:
  push:
    branches:
      - main
    paths:
      - lambda/**
      - .github/workflows/ci.yml

jobs:
  CD:
    runs-on: ubuntu-latest

    name: build and deploy lambda
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
          mkdir lambda/package
          ls -la
          pip install -r lambda/requirements.txt -t lambda/package
          cp lambda/lambda_function.py lambda/package/
          cd lambda/package/
          zip -r ../lambda_function.zip .

    - name: Create or Update Lambda Function
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
        PROVIDERS: ${{ var.PROVIDERS }}
      run: |
        if aws lambda get-function --function-name GBFSDataFetcher > /dev/null 2>&1; then
          echo "Lambda function already exists. Updating code..."
          aws lambda update-function-code \
            --function-name GBFSDataFetcher \
            --zip-file fileb://lambda/lambda_function.zip
          aws lambda update-function-configuration \
            --function-name GBFSDataFetcher \
            --environment Variables="{rds_password=$RDS_PASSWORD,providers='$PROVIDERS'}"
        else
          echo "Creating new Lambda function..."
          aws lambda create-function \
            --function-name GBFSDataFetcher \
            --runtime python3.9 \
            --role arn:aws:lambda:us-east-1:164008106637:function:GBFSDataFetcher \
            --handler lambda_function.lambda_handler \
            --zip-file fileb://lambda/lambda_function.zip \
            --environment Variables="{rds_password=$RDS_PASSWORD,providers='$PROVIDERS'}"
        fi